//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cobro
    {
        public System.DateTime fecha { get; set; }
        public int IDPlanCobro { get; set; }
        public int IDResidencia { get; set; }
        public decimal total { get; set; }
        public bool pagado { get; set; }
        public Nullable<System.DateTime> fechaPago { get; set; }
    
        public virtual PlanCobro PlanCobro { get; set; }
        public virtual Residencia Residencia { get; set; }
    }
}
