//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cobro
    {
        public System.DateTime fecha { get; set; }
        public int planCobro { get; set; }
        public int residencia { get; set; }
        public decimal total { get; set; }
        public bool pagado { get; set; }
        public System.DateTime fechaPago { get; set; }
    
        public virtual PlanCobro PlanCobro1 { get; set; }
        public virtual Residencia Residencia1 { get; set; }
    }
}
