//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EdificioPublico : Edificio
    {
        public EdificioPublico()
        {
            this.Reserva = new HashSet<Reserva>();
        }
    
        public short espacioPersonas { get; set; }
        public short espacioParqueo { get; set; }
        public decimal montoHoraReserva { get; set; }
    
        public virtual ICollection<Reserva> Reserva { get; set; }
    }
}
