//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Edificio
    {
        public int ID { get; set; }
        public string calle { get; set; }
        public string avenida { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fechaConst { get; set; }
        public byte estado { get; set; }
    }
}
