//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noticias
    {
        public string nombre { get; set; }
        public string contenido { get; set; }
        public System.DateTime fecha { get; set; }
        public byte[] imagen { get; set; }
    }
}
