//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanCobro
    {
        public PlanCobro()
        {
            this.Cobro = new HashSet<Cobro>();
            this.Rubro = new HashSet<Rubro>();
        }
    
        public int ID { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public bool automatico { get; set; }
    
        public virtual ICollection<Cobro> Cobro { get; set; }
        public virtual ICollection<Rubro> Rubro { get; set; }
    }
}
