//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public System.DateTime fecha { get; set; }
        public int edificio { get; set; }
        public string motivo { get; set; }
        public byte estado { get; set; }
        public int usuario { get; set; }
        public byte horas { get; set; }
    
        public virtual EdificioPublico EdificioPublico { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
