//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Residencia : Edificio
    {
        public Residencia()
        {
            this.Cobro = new HashSet<Cobro>();
        }
    
        public decimal montoMensual { get; set; }
        public byte cantInquilinos { get; set; }
        public byte espacioGaraje { get; set; }
        public byte habitaciones { get; set; }
        public int dueno { get; set; }
    
        public virtual ICollection<Cobro> Cobro { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
