//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Incidencia = new HashSet<Incidencia>();
            this.Reserva = new HashSet<Reserva>();
            this.Residencia = new HashSet<Residencia>();
        }
    
        public int ID { get; set; }
        public string nombre { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        public byte[] contrasena { get; set; }
        public string cedula { get; set; }
        public byte tipo { get; set; }
    
        public virtual ICollection<Incidencia> Incidencia { get; set; }
        public virtual ICollection<Reserva> Reserva { get; set; }
        public virtual ICollection<Residencia> Residencia { get; set; }
    }
}
